module.exports = {
  auth:          require('./auth'),
  businesses:    require('./businesses'),
  accounts:      require('./accounts'),
  journal:       require('./journal'),
  payable:       require('./payable'),
  receivable:    require('./receivable'),
  payroll:       require('./payroll'),
  bir:           require('./bir'),
  dashboard:     require('./dashboard'),
  settings:      require('./settings'),
  customReports: require('./customReports'),
  inventory:     require('./inventory'),
  remittance:    require('./remittance'),
  expense:       require('./expense'),
  audit:         require('./audit'),
  attachments:   require('./attachments'),
  purchaseOrders:require('./purchaseOrders'),
  assets:        require('./assets'),
  bank:          require('./bank'),
  budget:        require('./budget'),
  recurring:     require('./recurring'),
  notifications: require('./notifications'),
  search:        require('./search'),
};
