module.exports = {
  auth:          require('./auth'),
  accounts:      require('./accounts'),
  journal:       require('./journal'),
  payable:       require('./payable'),
  receivable:    require('./receivable'),
  payroll:       require('./payroll'),
  bir:           require('./bir'),
  dashboard:     require('./dashboard'),
  settings:      require('./settings'),
  customReports: require('./customReports'),
  inventory:     require('./inventory'),
  remittance:    require('./remittance'),
  expense:       require('./expense'),
};
